"""Add banner_name and subtitle to banners

Revision ID: 678447775629
Revises: 
Create Date: 2025-11-12 12:29:30.466498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678447775629'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('banner_name', sa.String(length=200), nullable=True))
    op.add_column('banners', sa.Column('subtitle', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banners', 'subtitle')
    op.drop_column('banners', 'banner_name')
    # ### end Alembic commands ###
