"""Add partner_id to stores

Revision ID: 8e8f12ad5f5e
Revises: add_renter_info_to_orders
Create Date: 2025-11-12 15:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8f12ad5f5e'
down_revision: Union[str, Sequence[str], None] = 'add_renter_info_to_orders'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_stores_partner_id', 'stores', 'partners', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stores_partner_id', 'stores', type_='foreignkey')
    op.drop_column('stores', 'partner_id')
    # ### end Alembic commands ###

